import type { Post } from "./types";

export const POSTS_C: Post[] = [
  {
    slug: "ai-calling-for-admissions",
    title: "AI Calling for Admissions: A Follow-Up Playbook",
    description: "Plan AI admissions calls for schools and coaching institutes: enquiry questions, parent call scripts, counsellor handoffs and a practical pilot scorecard.",
    category: "Playbooks",
    keywords: ["AI calling for admissions", "AI calling for coaching institutes", "admission enquiry follow up", "education voice AI", "parent enquiry call script"],
    published: "2026-10-10",
    readMinutes: 5,
    pages: ["/industries/education/", "/use-cases/application-follow-up/", "/use-cases/instant-lead-callback/", "/agent-builder/"],
  },
  {
    slug: "ai-calling-for-real-estate",
    title: "AI Calling for Real Estate: Qualify and Book Visits",
    description: "Build a real estate AI calling workflow with buyer qualification questions, a site visit script, project fact checks and clear handoffs to property sales reps.",
    category: "Playbooks",
    keywords: ["AI calling for real estate", "real estate lead qualification", "AI telecaller for real estate", "site visit booking script", "property lead follow up"],
    published: "2026-10-10",
    readMinutes: 5,
    pages: ["/industries/real-estate/", "/use-cases/appointment-booking/", "/use-cases/lead-qualification/"],
  },
  {
    slug: "ai-lead-qualification-questions",
    title: "AI Lead Qualification: Questions, Scoring and Handoffs",
    description: "Design an AI lead qualification call with useful questions, evidence-based outcomes and human handoffs. Includes a sample script and a pilot measurement plan.",
    category: "Guides",
    keywords: ["AI lead qualification", "lead qualification questions", "AI lead scoring", "AI sales qualification", "lead qualification call script"],
    published: "2026-10-10",
    readMinutes: 5,
    pages: ["/use-cases/lead-qualification/", "/ai-telecaller/", "/ai-voice-agents/", "/call-intelligence/"],
  },
  {
    slug: "ai-appointment-reminder-calls",
    title: "AI Appointment Reminder Calls: Scripts and Workflows",
    description: "Set up AI appointment reminder calls with confirmation scripts, rescheduling rules and clear outcomes. Measure attendance without confusing it with bookings.",
    category: "Playbooks",
    keywords: ["AI appointment reminder calls", "automated appointment confirmation", "appointment reminder call script", "AI appointment scheduling", "reduce appointment no shows"],
    published: "2026-10-10",
    readMinutes: 5,
    pages: ["/use-cases/appointment-booking/", "/use-cases/event-confirmation/", "/automations/"],
  },
  {
    slug: "ai-receptionist-for-small-business",
    title: "AI Receptionist for Small Business: A Setup Guide",
    description: "Plan an AI receptionist for a small business: approved answers, caller routing, human transfers, after-hours handling and a practical checklist for test calls.",
    category: "Guides",
    keywords: ["AI receptionist for small business", "AI phone receptionist India", "inbound AI voice agent", "automated call answering", "after hours phone answering"],
    published: "2026-10-10",
    readMinutes: 5,
    pages: ["/use-cases/ai-receptionist/", "/ai-voice-agents/", "/how-it-works/", "/agent-builder/"],
  },
  {
    slug: "ai-calling-crm-integration",
    title: "AI Calling CRM Integration: A Webhook Workflow Guide",
    description: "Map an AI calling CRM workflow from lead capture to call outcomes, rep assignment and follow-up. Covers webhooks, field mapping, duplicate events and testing.",
    category: "Guides",
    keywords: ["AI calling CRM integration", "AI calling webhook", "voice AI CRM workflow", "automated lead follow up", "AI calling API"],
    published: "2026-10-10",
    readMinutes: 5,
    pages: ["/automations/", "/use-cases/instant-lead-callback/", "/use-cases/lead-qualification/", "/how-it-works/"],
  },
];
